//--------------------------------------------------------------------------
/*! \file pre_spike_time_in_sim/test.cc

\brief Main test code that is part of the feature testing
suite of minimal models with known analytic outcomes that are used for continuous integration testing.
*/
//--------------------------------------------------------------------------
// Standard C includes
#include <cmath>

// Google test includes
#include "gtest/gtest.h"

// Autogenerated simulation code includess
#include "pre_spike_time_in_sim_CODE/definitions.h"

// **NOTE** base-class for simulation tests must be
// included after auto-generated globals are includes
#include "../../utils/simulation_test.h"

// Combine neuron and synapse policies together to build variable-testing fixture
class SimTest : public SimulationTest
{
public:
    void Simulate()
    {
        while(t < 200.0f) {
            StepGeNN();

            // Ignore first timestep as no postsynaptic events will be processed so wsyn is in it's initial state
            if(t > DT) {
                // Loop through neurons
                for(unsigned int i = 0; i < 10; i++) {
                    // Calculate time of spikes we SHOULD be reading
                    // **NOTE** we delay by 21 timesteps because:
                    // 1) delay = 20
                    // 2) presynaptic kernel reads spike times from PREVIOUS timestep
                    const float delayedTime = (scalar)i + 21.0f + (10.0f * std::floor((t - 22.0f - (scalar)i) / 10.0f));
                    
                    // If, theoretically, spike would have arrived before delay wsyn won't have been updated so should be zero
                    if(delayedTime < 21.0f) {
                        ASSERT_FLOAT_EQ(wsyn[i], 0.0);
                    }
                    else {
                        ASSERT_FLOAT_EQ(wsyn[i], delayedTime);
                    }
                }
            }
        }
    }
};

TEST_F(SimTest, PreSpikeTimeInPostLearn)
{
    Simulate();
}
