#--------------------------------------------------------------------------
#   Author: Thomas Nowotny
#  
#   Institute: Informatics
#              University of Sussex 
#              Brighton BN1 9QJ, UK
#  
#   email to:  t.nowotny@sussex.ac.uk
#  
#   initial version: 2014-06-26
#  
#--------------------------------------------------------------------------

CXXFLAGS =-Wall -Winline -O3 -g -I$(GENNPATH)/lib/include/numlib

all: generate_run

clean:
	$(RM) generate_run
