#! /bin/bash

doxygen doxygen/genn-doxygen.conf
doxygen/fixLatexPageref.pl documentation/latex/files.tex
doxygen/fixLatexPageref.pl documentation/latex/hierarchy.tex
doxygen/fixLatexPageref.pl documentation/latex/annotated.tex
doxygen/fixLatexLabels.pl documentation/latex/refman.tex
doxygen/replace_in_files.pl "\\\\backmatter" "" documentation/latex/refman.tex
