#! /bin/bash

# Run doxygen
(cat doxygen/genn-doxygen.conf  ; echo "PROJECT_NUMBER=`cat version.txt`") | doxygen -

# Apply scripts to fixup tex output
doxygen/fixLatexPageref.pl documentation/latex/files.tex
doxygen/fixLatexPageref.pl documentation/latex/hierarchy.tex
doxygen/fixLatexPageref.pl documentation/latex/annotated.tex
doxygen/fixLatexLabels.pl documentation/latex/refman.tex
doxygen/replace_in_files.pl "\\\\backmatter" "" documentation/latex/refman.tex

# Run doxyrest to generate rest format documentation
doxyrest -c docs/doxyrest-config.lua -F $DOXYREST_FRAME_DIR/common/ -F $DOXYREST_FRAME_DIR/cfamily 
