var searchData=
[
  ['activatedirectinput',['activateDirectInput',['../dc/de5/classNNmodel.html#a42efe11d1a2fbab01e3a46b08698c1bc',1,'NNmodel']]],
  ['addextraglobalneuronparams',['addExtraGlobalNeuronParams',['../dc/dfa/classSynapseGroup.html#ad57bb85759076e1410979b4c6f426081',1,'SynapseGroup']]],
  ['addextraglobalparams',['addExtraGlobalParams',['../d7/d3b/classNeuronGroup.html#a9f12603e7de577a4b75bfd91f0e8146e',1,'NeuronGroup']]],
  ['addextraglobalpostlearnparams',['addExtraGlobalPostLearnParams',['../dc/dfa/classSynapseGroup.html#a8c02e60c4cf7572eebec674d690e7575',1,'SynapseGroup']]],
  ['addextraglobalsynapsedynamicsparams',['addExtraGlobalSynapseDynamicsParams',['../dc/dfa/classSynapseGroup.html#a29dd18a24113004d1efec5363365abdb',1,'SynapseGroup']]],
  ['addextraglobalsynapseparams',['addExtraGlobalSynapseParams',['../dc/dfa/classSynapseGroup.html#abd939b244af1b5052f6c5a0bb3acd5ca',1,'SynapseGroup']]],
  ['addinsyn',['addInSyn',['../d7/d3b/classNeuronGroup.html#af012e41b13a59fe348fc7b4959dbe2ff',1,'NeuronGroup']]],
  ['addneuronpopulation',['addNeuronPopulation',['../dc/de5/classNNmodel.html#a8d7d593837882775dfb89a9780c06fab',1,'NNmodel::addNeuronPopulation(const string &amp;, unsigned int, unsigned int, const double *, const double *)'],['../dc/de5/classNNmodel.html#a36cd02056ae5920d278a3afb89fd2eaa',1,'NNmodel::addNeuronPopulation(const string &amp;, unsigned int, unsigned int, const vector&lt; double &gt; &amp;, const vector&lt; double &gt; &amp;)'],['../dc/de5/classNNmodel.html#a4e6d344e8d320d5775b06b1984a37c98',1,'NNmodel::addNeuronPopulation(const string &amp;name, unsigned int size, const NeuronModel *model, const typename NeuronModel::ParamValues &amp;paramValues, const typename NeuronModel::VarValues &amp;varInitialisers)'],['../dc/de5/classNNmodel.html#a87ca7a3ab6ba280f8bf65cff967f2d79',1,'NNmodel::addNeuronPopulation(const string &amp;name, unsigned int size, const typename NeuronModel::ParamValues &amp;paramValues, const typename NeuronModel::VarValues &amp;varInitialisers)']]],
  ['addoutsyn',['addOutSyn',['../d7/d3b/classNeuronGroup.html#a6a7c5fa4577c48b6682b60a3b07b9dc5',1,'NeuronGroup']]],
  ['addspkeventcondition',['addSpkEventCondition',['../d7/d3b/classNeuronGroup.html#a4b0aa0380df4cf7d51ec68caf9a703c2',1,'NeuronGroup']]],
  ['addsynapsepopulation',['addSynapsePopulation',['../dc/de5/classNNmodel.html#aae817535d08ab6b35ef1e2348b03a37c',1,'NNmodel::addSynapsePopulation(const string &amp;name, unsigned int syntype, SynapseConnType conntype, SynapseGType gtype, const string &amp;src, const string &amp;trg, const double *p)'],['../dc/de5/classNNmodel.html#a95a917ca52397247174381f12757bac4',1,'NNmodel::addSynapsePopulation(const string &amp;, unsigned int, SynapseConnType, SynapseGType, unsigned int, unsigned int, const string &amp;, const string &amp;, const double *, const double *, const double *)'],['../dc/de5/classNNmodel.html#a8b558e074f68ef4cc0221a5582a786b5',1,'NNmodel::addSynapsePopulation(const string &amp;, unsigned int, SynapseConnType, SynapseGType, unsigned int, unsigned int, const string &amp;, const string &amp;, const double *, const double *, const double *, const double *)'],['../dc/de5/classNNmodel.html#a09fa20aa43b21db5bf88784a1a8524bc',1,'NNmodel::addSynapsePopulation(const string &amp;, unsigned int, SynapseConnType, SynapseGType, unsigned int, unsigned int, const string &amp;, const string &amp;, const vector&lt; double &gt; &amp;, const vector&lt; double &gt; &amp;, const vector&lt; double &gt; &amp;, const vector&lt; double &gt; &amp;)'],['../dc/de5/classNNmodel.html#a0238c35c1bd3de683c385edd7bf83d02',1,'NNmodel::addSynapsePopulation(const string &amp;name, SynapseMatrixType mtype, unsigned int delaySteps, const string &amp;src, const string &amp;trg, const WeightUpdateModel *wum, const typename WeightUpdateModel::ParamValues &amp;weightParamValues, const typename WeightUpdateModel::VarValues &amp;weightVarInitialisers, const PostsynapticModel *psm, const typename PostsynapticModel::ParamValues &amp;postsynapticParamValues, const typename PostsynapticModel::VarValues &amp;postsynapticVarInitialisers)'],['../dc/de5/classNNmodel.html#a47a23c344993756fbb5d8cd524123e5b',1,'NNmodel::addSynapsePopulation(const string &amp;name, SynapseMatrixType mtype, unsigned int delaySteps, const string &amp;src, const string &amp;trg, const typename WeightUpdateModel::ParamValues &amp;weightParamValues, const typename WeightUpdateModel::VarValues &amp;weightVarInitialisers, const typename PostsynapticModel::ParamValues &amp;postsynapticParamValues, const typename PostsynapticModel::VarValues &amp;postsynapticVarInitialisers)']]]
];
