// Google test includes
#include "gtest/gtest.h"

// Autogenerated simulation code includess
#include "post_vars_in_post_learn_CODE/definitions.h"

// **NOTE** base-class for simulation tests must be
// included after auto-generated globals are includes
#include "../../utils/simulation_test_post_vars.h"

TEST_P(SimulationTestPostVars, AcceptableError)
{
  float err = Simulate(
    [](float t)
    {
        return (t > 2.1001) && (fmod(t - 2*DT+5e-5, 2.0f) < 1e-4);
    });

  // Check total error is less than some tolerance
  EXPECT_LT(err, 2e-2);
}

#ifndef CPU_ONLY
auto simulatorBackends = ::testing::Values(true, false);
#else
auto simulatorBackends = ::testing::Values(false);
#endif

INSTANTIATE_TEST_CASE_P(PostLearn,
                        SimulationTestPostVars,
                        simulatorBackends);