var namespaceCodeGenerator =
[
    [ "CUDA", "d1/df6/namespaceCodeGenerator_1_1CUDA.html", "d1/df6/namespaceCodeGenerator_1_1CUDA" ],
    [ "PresynapticUpdateStrategySIMT", "d1/d45/namespaceCodeGenerator_1_1PresynapticUpdateStrategySIMT.html", "d1/d45/namespaceCodeGenerator_1_1PresynapticUpdateStrategySIMT" ],
    [ "SingleThreadedCPU", "db/d8c/namespaceCodeGenerator_1_1SingleThreadedCPU.html", "db/d8c/namespaceCodeGenerator_1_1SingleThreadedCPU" ],
    [ "BackendBase", "d3/d15/classCodeGenerator_1_1BackendBase.html", "d3/d15/classCodeGenerator_1_1BackendBase" ],
    [ "BackendSIMT", "d1/de3/classCodeGenerator_1_1BackendSIMT.html", "d1/de3/classCodeGenerator_1_1BackendSIMT" ],
    [ "CodeStream", "d9/df8/classCodeGenerator_1_1CodeStream.html", "d9/df8/classCodeGenerator_1_1CodeStream" ],
    [ "GroupMerged", "df/dfd/classCodeGenerator_1_1GroupMerged.html", "df/dfd/classCodeGenerator_1_1GroupMerged" ],
    [ "MemAlloc", "d2/d06/classCodeGenerator_1_1MemAlloc.html", "d2/d06/classCodeGenerator_1_1MemAlloc" ],
    [ "ModelSpecMerged", "de/d52/classCodeGenerator_1_1ModelSpecMerged.html", "de/d52/classCodeGenerator_1_1ModelSpecMerged" ],
    [ "NeuronGroupMergedBase", "d7/dee/classCodeGenerator_1_1NeuronGroupMergedBase.html", "d7/dee/classCodeGenerator_1_1NeuronGroupMergedBase" ],
    [ "NeuronInitGroupMerged", "dd/d98/classCodeGenerator_1_1NeuronInitGroupMerged.html", "dd/d98/classCodeGenerator_1_1NeuronInitGroupMerged" ],
    [ "NeuronSpikeQueueUpdateGroupMerged", "d5/dbc/classCodeGenerator_1_1NeuronSpikeQueueUpdateGroupMerged.html", "d5/dbc/classCodeGenerator_1_1NeuronSpikeQueueUpdateGroupMerged" ],
    [ "NeuronUpdateGroupMerged", "d3/d7d/classCodeGenerator_1_1NeuronUpdateGroupMerged.html", "d3/d7d/classCodeGenerator_1_1NeuronUpdateGroupMerged" ],
    [ "PostsynapticUpdateGroupMerged", "dd/d96/classCodeGenerator_1_1PostsynapticUpdateGroupMerged.html", "dd/d96/classCodeGenerator_1_1PostsynapticUpdateGroupMerged" ],
    [ "PreferencesBase", "d1/d7a/structCodeGenerator_1_1PreferencesBase.html", "d1/d7a/structCodeGenerator_1_1PreferencesBase" ],
    [ "PresynapticUpdateGroupMerged", "df/df5/classCodeGenerator_1_1PresynapticUpdateGroupMerged.html", "df/df5/classCodeGenerator_1_1PresynapticUpdateGroupMerged" ],
    [ "Substitutions", "de/d22/classCodeGenerator_1_1Substitutions.html", "de/d22/classCodeGenerator_1_1Substitutions" ],
    [ "SupportCodeMerged", "d1/db8/classCodeGenerator_1_1SupportCodeMerged.html", "d1/db8/classCodeGenerator_1_1SupportCodeMerged" ],
    [ "SynapseConnectivityHostInitGroupMerged", "d9/df1/classCodeGenerator_1_1SynapseConnectivityHostInitGroupMerged.html", "d9/df1/classCodeGenerator_1_1SynapseConnectivityHostInitGroupMerged" ],
    [ "SynapseConnectivityInitGroupMerged", "de/d5d/classCodeGenerator_1_1SynapseConnectivityInitGroupMerged.html", "de/d5d/classCodeGenerator_1_1SynapseConnectivityInitGroupMerged" ],
    [ "SynapseDendriticDelayUpdateGroupMerged", "d4/d7f/classCodeGenerator_1_1SynapseDendriticDelayUpdateGroupMerged.html", "d4/d7f/classCodeGenerator_1_1SynapseDendriticDelayUpdateGroupMerged" ],
    [ "SynapseDenseInitGroupMerged", "d1/d09/classCodeGenerator_1_1SynapseDenseInitGroupMerged.html", "d1/d09/classCodeGenerator_1_1SynapseDenseInitGroupMerged" ],
    [ "SynapseDynamicsGroupMerged", "d3/d00/classCodeGenerator_1_1SynapseDynamicsGroupMerged.html", "d3/d00/classCodeGenerator_1_1SynapseDynamicsGroupMerged" ],
    [ "SynapseGroupMergedBase", "d7/d78/classCodeGenerator_1_1SynapseGroupMergedBase.html", "d7/d78/classCodeGenerator_1_1SynapseGroupMergedBase" ],
    [ "SynapseSparseInitGroupMerged", "db/df8/classCodeGenerator_1_1SynapseSparseInitGroupMerged.html", "db/df8/classCodeGenerator_1_1SynapseSparseInitGroupMerged" ],
    [ "TeeBuf", "d8/d5e/classCodeGenerator_1_1TeeBuf.html", "d8/d5e/classCodeGenerator_1_1TeeBuf" ],
    [ "TeeStream", "d7/d71/classCodeGenerator_1_1TeeStream.html", "d7/d71/classCodeGenerator_1_1TeeStream" ]
];