##--------------------------------------------------------------------------
##   Author: Thomas Nowotny
##
##   Institute: Center for Computational Neuroscience and Robotics
##              University of Sussex
##              Falmer, Brighton BN1 9QJ, UK
##
##   email to:  T.Nowotny@sussex.ac.uk
##
##   initial version: 2010-02-07
##
##--------------------------------------------------------------------------

EXECUTABLE         :=Izh_sim_sparse
SOURCES            :=$(EXECUTABLE).cc Izh_sparse_model.cc
OPTIMIZATIONFLAGS  :=-O3

include	$(GENN_PATH)/userproject/include/makefile_common_gnu.mk