var searchData=
[
  ['add_5fcurrent_5fsource',['add_current_source',['../db/d57/classpygenn_1_1genn__model_1_1GeNNModel.html#a20b03cbc0200038e8dd9950553fe5152',1,'pygenn::genn_model::GeNNModel']]],
  ['add_5fextra_5fglobal_5fparam',['add_extra_global_param',['../dc/dc9/classpygenn_1_1genn__groups_1_1NeuronGroup.html#a870207702ea6ffc852401643a2dd9960',1,'pygenn.genn_groups.NeuronGroup.add_extra_global_param()'],['../d5/d49/classpygenn_1_1genn__groups_1_1SynapseGroup.html#ac5806934aaf2a806aa7d5e6199f07335',1,'pygenn.genn_groups.SynapseGroup.add_extra_global_param()'],['../da/d83/classpygenn_1_1genn__groups_1_1CurrentSource.html#ae6e20b0ea58f3e85341b835b07f5126c',1,'pygenn.genn_groups.CurrentSource.add_extra_global_param()']]],
  ['add_5fneuron_5fpopulation',['add_neuron_population',['../db/d57/classpygenn_1_1genn__model_1_1GeNNModel.html#a100324e214546094fced5e66fb0582d4',1,'pygenn::genn_model::GeNNModel']]],
  ['add_5fsynapse_5fpopulation',['add_synapse_population',['../db/d57/classpygenn_1_1genn__model_1_1GeNNModel.html#ab573f92c82ec25d5c80f94070b6008c0',1,'pygenn::genn_model::GeNNModel']]],
  ['add_5fto',['add_to',['../dc/dc9/classpygenn_1_1genn__groups_1_1NeuronGroup.html#a597150844c84e62e5e98bbb18774b1cc',1,'pygenn.genn_groups.NeuronGroup.add_to()'],['../d5/d49/classpygenn_1_1genn__groups_1_1SynapseGroup.html#a7661170e06a9fbc945f697599618a285',1,'pygenn.genn_groups.SynapseGroup.add_to()'],['../da/d83/classpygenn_1_1genn__groups_1_1CurrentSource.html#ac48d2951f6388fd03df83f80bb8e1b97',1,'pygenn.genn_groups.CurrentSource.add_to()']]],
  ['addcurrentsource',['addCurrentSource',['../da/dfd/classModelSpec.html#aaf260ae8ffd52473b61a27974867c3e3',1,'ModelSpec::addCurrentSource(const std::string &amp;currentSourceName, const CurrentSourceModel *model, const std::string &amp;targetNeuronGroupName, const typename CurrentSourceModel::ParamValues &amp;paramValues, const typename CurrentSourceModel::VarValues &amp;varInitialisers)'],['../da/dfd/classModelSpec.html#a54bfff6bcd9ae2bf4d3424177a68265c',1,'ModelSpec::addCurrentSource(const std::string &amp;currentSourceName, const std::string &amp;targetNeuronGroupName, const typename CurrentSourceModel::ParamValues &amp;paramValues, const typename CurrentSourceModel::VarValues &amp;varInitialisers)']]],
  ['addfuncsubstitution',['addFuncSubstitution',['../de/d22/classCodeGenerator_1_1Substitutions.html#a61c71d0dc4863950a652ecce2fa1b843',1,'CodeGenerator::Substitutions']]],
  ['addinsyn',['addInSyn',['../d7/d3b/classNeuronGroup.html#ae7e850440a142d86fefa78155ead34cb',1,'NeuronGroup']]],
  ['addneuronpopulation',['addNeuronPopulation',['../da/dfd/classModelSpec.html#a0b765be273f3c6cec15092d7dbfdd52b',1,'ModelSpec::addNeuronPopulation(const std::string &amp;name, unsigned int size, const NeuronModel *model, const typename NeuronModel::ParamValues &amp;paramValues, const typename NeuronModel::VarValues &amp;varInitialisers, int hostID=0)'],['../da/dfd/classModelSpec.html#a5eec26674996c3504f1c85b1e190f82f',1,'ModelSpec::addNeuronPopulation(const std::string &amp;name, unsigned int size, const typename NeuronModel::ParamValues &amp;paramValues, const typename NeuronModel::VarValues &amp;varInitialisers, int hostID=0)']]],
  ['addoutsyn',['addOutSyn',['../d7/d3b/classNeuronGroup.html#a4b073fc74ad5b0ba60811487525569ee',1,'NeuronGroup']]],
  ['addspkeventcondition',['addSpkEventCondition',['../d7/d3b/classNeuronGroup.html#a4b0aa0380df4cf7d51ec68caf9a703c2',1,'NeuronGroup']]],
  ['addsynapsepopulation',['addSynapsePopulation',['../da/dfd/classModelSpec.html#abd4e9128a5d4f5f993907134218af0c2',1,'ModelSpec::addSynapsePopulation(const std::string &amp;name, SynapseMatrixType mtype, unsigned int delaySteps, const std::string &amp;src, const std::string &amp;trg, const WeightUpdateModel *wum, const typename WeightUpdateModel::ParamValues &amp;weightParamValues, const typename WeightUpdateModel::VarValues &amp;weightVarInitialisers, const typename WeightUpdateModel::PreVarValues &amp;weightPreVarInitialisers, const typename WeightUpdateModel::PostVarValues &amp;weightPostVarInitialisers, const PostsynapticModel *psm, const typename PostsynapticModel::ParamValues &amp;postsynapticParamValues, const typename PostsynapticModel::VarValues &amp;postsynapticVarInitialisers, const InitSparseConnectivitySnippet::Init &amp;connectivityInitialiser=uninitialisedConnectivity())'],['../da/dfd/classModelSpec.html#a0bde9e959e2d306b6af799e5b9fb9eaa',1,'ModelSpec::addSynapsePopulation(const std::string &amp;name, SynapseMatrixType mtype, unsigned int delaySteps, const std::string &amp;src, const std::string &amp;trg, const typename WeightUpdateModel::ParamValues &amp;weightParamValues, const typename WeightUpdateModel::VarValues &amp;weightVarInitialisers, const typename PostsynapticModel::ParamValues &amp;postsynapticParamValues, const typename PostsynapticModel::VarValues &amp;postsynapticVarInitialisers, const InitSparseConnectivitySnippet::Init &amp;connectivityInitialiser=uninitialisedConnectivity())'],['../da/dfd/classModelSpec.html#a9c0d07277fbdedf094f06279d13f4d54',1,'ModelSpec::addSynapsePopulation(const std::string &amp;name, SynapseMatrixType mtype, unsigned int delaySteps, const std::string &amp;src, const std::string &amp;trg, const typename WeightUpdateModel::ParamValues &amp;weightParamValues, const typename WeightUpdateModel::VarValues &amp;weightVarInitialisers, const typename WeightUpdateModel::PreVarValues &amp;weightPreVarInitialisers, const typename WeightUpdateModel::PostVarValues &amp;weightPostVarInitialisers, const typename PostsynapticModel::ParamValues &amp;postsynapticParamValues, const typename PostsynapticModel::VarValues &amp;postsynapticVarInitialisers, const InitSparseConnectivitySnippet::Init &amp;connectivityInitialiser=uninitialisedConnectivity())']]],
  ['addtype',['addType',['../d3/d15/classCodeGenerator_1_1BackendBase.html#a70d012f95c388904a7ea64a5509ee124',1,'CodeGenerator::BackendBase']]],
  ['addvarsubstitution',['addVarSubstitution',['../de/d22/classCodeGenerator_1_1Substitutions.html#ae3ed06630ef19dce975fd16651768c32',1,'CodeGenerator::Substitutions']]],
  ['apply',['apply',['../de/d22/classCodeGenerator_1_1Substitutions.html#ae2f104d7fb3d30afa560f4ea00eed80a',1,'CodeGenerator::Substitutions']]]
];
