// Google test includes
#include "gtest/gtest.h"

// Autogenerated simulation code includess
#include "pre_vars_in_post_learn_sparse_CODE/definitions.h"

// **NOTE** base-class for simulation tests must be
// included after auto-generated globals are includes
#include "../../utils/simulation_test_vars.h"
#include "../../utils/simulation_neuron_policy_pre_var.h"
#include "../../utils/simulation_synapse_policy_sparse.h"

// Combine neuron and synapse policies together to build variable-testing fixture
typedef SimulationTestVars<SimulationNeuronPolicyPreVar, SimulationSynapsePolicySparse> SimulationTestPreVarsSparse;

TEST_P(SimulationTestPreVarsSparse, AcceptableError)
{
  initpre_vars_in_post_learn_sparse();

  float err = Simulate(
    [](unsigned int i, unsigned int d, unsigned int j, float t, float &newX)
    {
        if ((t > 2.0001) && (fmod(t-2*DT+5e-5,2.0f) < 1e-4))
        {
            newX = t-DT-(d+1)*DT+10*j;
            return true;
        }
        else
        {
          return false;
        }
    });

  // Check total error is less than some tolerance
  EXPECT_LT(err, 3e-3);
}

#ifndef CPU_ONLY
auto simulatorBackends = ::testing::Values(true, false);
#else
auto simulatorBackends = ::testing::Values(false);
#endif

INSTANTIATE_TEST_CASE_P(PostLearn,
                        SimulationTestPreVarsSparse,
                        simulatorBackends);