##--------------------------------------------------------------------------
##   Author: Thomas Nowotny
##
##   Institute: Center for Computational Neuroscience and Robotics
##              University of Sussex
##            Falmer, Brighton BN1 9QJ, UK
##
##   email to:  T.Nowotny@sussex.ac.uk
##
##   initial version: 2010-02-07
##
##--------------------------------------------------------------------------

ROOTDIR         := $(GeNNPATH)/lib/src
EXECUTABLE      := generateALL
SOURCES         := generateALL.cc utils.cc

INCLUDE_FLAGS   :=
LINK_FLAGS      :=
CCFLAGS         :=
NVCCFLAGS       :=

ifdef COMSPEC
	include	$(GeNNPATH)/lib/include/makefile_common_cygwin.mk
else
	include	$(GeNNPATH)/lib/include/makefile_common.mk
endif
