// Google test includes
#include "gtest/gtest.h"

// Autogenerated simulation code includess
#include "pre_vars_in_sim_code_event_CODE/definitions.h"

// **NOTE** base-class for simulation tests must be
// included after auto-generated globals are includes
#include "../../utils/simulation_test_vars.h"
#include "../../utils/simulation_neuron_policy_pre_var.h"
#include "../../utils/simulation_synapse_policy_dense.h"

// Combine neuron and synapse policies together to build variable-testing fixture
typedef SimulationTestVars<SimulationNeuronPolicyPreVar, SimulationSynapsePolicyDense> SimulationTestPreVars;

TEST_P(SimulationTestPreVars, AcceptableError)
{
  float err = Simulate(
    [](unsigned int d, unsigned int j, unsigned int k, float t, float &newX)
    {
        if ((t > d*DT+0.1001) && (fmod(t-2*DT-d*DT+5e-5+10*j,(float) (2*(d+1))) < 1e-4))
        {
            newX = t-2*DT-d*DT+10*j;
            return true;
        }
        else
        {
          return false;
        }
    });

  // Check total error is less than some tolerance
  EXPECT_LT(err, 1e-2);
}

#ifndef CPU_ONLY
auto simulatorBackends = ::testing::Values(true, false);
#else
auto simulatorBackends = ::testing::Values(false);
#endif

INSTANTIATE_TEST_CASE_P(SimCodeEvent,
                        SimulationTestPreVars,
                        simulatorBackends);