var annotated =
[
    [ "classIzh", "de/dba/classclassIzh.html", "de/dba/classclassIzh" ],
    [ "classol", "d1/d16/classclassol.html", "d1/d16/classclassol" ],
    [ "CodeHelper", "d1/d03/classCodeHelper.html", "d1/d03/classCodeHelper" ],
    [ "CStopWatch", "d9/de8/classCStopWatch.html", "d9/de8/classCStopWatch" ],
    [ "dpclass", "db/de6/classdpclass.html", "db/de6/classdpclass" ],
    [ "errTupel", "d4/da7/structerrTupel.html", "d4/da7/structerrTupel" ],
    [ "expDecayDp", "da/d0d/classexpDecayDp.html", "da/d0d/classexpDecayDp" ],
    [ "inputSpec", "de/dad/structinputSpec.html", "de/dad/structinputSpec" ],
    [ "neuronModel", "d3/d64/structneuronModel.html", "d3/d64/structneuronModel" ],
    [ "neuronpop", "de/d18/classneuronpop.html", "de/d18/classneuronpop" ],
    [ "NNmodel", "dc/de5/classNNmodel.html", "dc/de5/classNNmodel" ],
    [ "Parameter", "d9/d00/structParameter.html", "d9/d00/structParameter" ],
    [ "postSynModel", "d8/dbb/structpostSynModel.html", "d8/dbb/structpostSynModel" ],
    [ "postVarsInPostLearn", "dd/df9/classpostVarsInPostLearn.html", "dd/df9/classpostVarsInPostLearn" ],
    [ "postVarsInPostLearn_sparse", "d3/d3e/classpostVarsInPostLearn__sparse.html", "d3/d3e/classpostVarsInPostLearn__sparse" ],
    [ "postVarsInSimCode", "d9/d04/classpostVarsInSimCode.html", "d9/d04/classpostVarsInSimCode" ],
    [ "postVarsInSimCode_sparse", "d7/d09/classpostVarsInSimCode__sparse.html", "d7/d09/classpostVarsInSimCode__sparse" ],
    [ "postVarsInSynapseDynamics", "d0/d21/classpostVarsInSynapseDynamics.html", "d0/d21/classpostVarsInSynapseDynamics" ],
    [ "postVarsInSynapseDynamics_sparse", "de/dd4/classpostVarsInSynapseDynamics__sparse.html", "de/dd4/classpostVarsInSynapseDynamics__sparse" ],
    [ "preVarsInPostLearn", "dc/d93/classpreVarsInPostLearn.html", "dc/d93/classpreVarsInPostLearn" ],
    [ "preVarsInPostLearn_sparse", "db/da4/classpreVarsInPostLearn__sparse.html", "db/da4/classpreVarsInPostLearn__sparse" ],
    [ "preVarsInSimCode", "d1/dc2/classpreVarsInSimCode.html", "d1/dc2/classpreVarsInSimCode" ],
    [ "preVarsInSimCode_sparse", "de/d14/classpreVarsInSimCode__sparse.html", "de/d14/classpreVarsInSimCode__sparse" ],
    [ "preVarsInSynapseDynamics", "d4/d6b/classpreVarsInSynapseDynamics.html", "d4/d6b/classpreVarsInSynapseDynamics" ],
    [ "preVarsInSynapseDynamics_sparse", "d3/d88/classpreVarsInSynapseDynamics__sparse.html", "d3/d88/classpreVarsInSynapseDynamics__sparse" ],
    [ "pwSTDP", "d0/dba/classpwSTDP.html", "d0/dba/classpwSTDP" ],
    [ "pwSTDP_userdef", "dd/d4e/classpwSTDP__userdef.html", "dd/d4e/classpwSTDP__userdef" ],
    [ "randomGauss", "d5/d45/classrandomGauss.html", "d5/d45/classrandomGauss" ],
    [ "randomGen", "d8/d3b/classrandomGen.html", "d8/d3b/classrandomGen" ],
    [ "rulkovdp", "d6/d9e/classrulkovdp.html", "d6/d9e/classrulkovdp" ],
    [ "Schmuker2014_classifier", "d1/dc3/classSchmuker2014__classifier.html", "d1/dc3/classSchmuker2014__classifier" ],
    [ "stdRG", "db/d09/classstdRG.html", "db/d09/classstdRG" ],
    [ "stopWatch", "d1/df5/structstopWatch.html", "d1/df5/structstopWatch" ],
    [ "SynDelay", "db/df7/classSynDelay.html", "db/df7/classSynDelay" ],
    [ "weightUpdateModel", "dd/db7/classweightUpdateModel.html", "dd/db7/classweightUpdateModel" ]
];