var files =
[
    [ "av.cc", "d0/d1c/av_8cc.html", "d0/d1c/av_8cc" ],
    [ "MBody1_project/model/classol_sim.cc", "d0/d9d/MBody1__project_2model_2classol__sim_8cc.html", "d0/d9d/MBody1__project_2model_2classol__sim_8cc" ],
    [ "MBody_delayedSyn_project/model/classol_sim.cc", "d2/d01/MBody__delayedSyn__project_2model_2classol__sim_8cc.html", "d2/d01/MBody__delayedSyn__project_2model_2classol__sim_8cc" ],
    [ "MBody_individualID_project/model/classol_sim.cc", "df/d5e/MBody__individualID__project_2model_2classol__sim_8cc.html", "df/d5e/MBody__individualID__project_2model_2classol__sim_8cc" ],
    [ "MBody_userdef_project/model/classol_sim.cc", "df/ded/MBody__userdef__project_2model_2classol__sim_8cc.html", "df/ded/MBody__userdef__project_2model_2classol__sim_8cc" ],
    [ "MBody1_project/model/classol_sim.h", "d5/d8d/MBody1__project_2model_2classol__sim_8h.html", "d5/d8d/MBody1__project_2model_2classol__sim_8h" ],
    [ "MBody_delayedSyn_project/model/classol_sim.h", "de/d54/MBody__delayedSyn__project_2model_2classol__sim_8h.html", "de/d54/MBody__delayedSyn__project_2model_2classol__sim_8h" ],
    [ "MBody_individualID_project/model/classol_sim.h", "d1/da6/MBody__individualID__project_2model_2classol__sim_8h.html", "d1/da6/MBody__individualID__project_2model_2classol__sim_8h" ],
    [ "MBody_userdef_project/model/classol_sim.h", "dc/ddd/MBody__userdef__project_2model_2classol__sim_8h.html", "dc/ddd/MBody__userdef__project_2model_2classol__sim_8h" ],
    [ "CodeHelper.h", "dd/d95/CodeHelper_8h.html", "dd/d95/CodeHelper_8h" ],
    [ "command_line_processing.h", "d3/d1c/command__line__processing_8h.html", "d3/d1c/command__line__processing_8h" ],
    [ "dpclass.h", "da/dc8/dpclass_8h.html", [
      [ "dpclass", "db/de6/classdpclass.html", "db/de6/classdpclass" ]
    ] ],
    [ "experiment.cc", "d8/d39/experiment_8cc.html", "d8/d39/experiment_8cc" ],
    [ "experiment.h", "dc/d02/experiment_8h.html", "dc/d02/experiment_8h" ],
    [ "extra_neurons.h", "db/d66/extra__neurons_8h.html", "db/d66/extra__neurons_8h" ],
    [ "lib/include/extra_postsynapses.h", "d1/de9/lib_2include_2extra__postsynapses_8h.html", "d1/de9/lib_2include_2extra__postsynapses_8h" ],
    [ "SpineML_to_GeNN/extra_postsynapses.h", "d9/d1d/SpineML__to__GeNN_2extra__postsynapses_8h.html", "d9/d1d/SpineML__to__GeNN_2extra__postsynapses_8h" ],
    [ "extra_weightupdates.h", "d4/d71/extra__weightupdates_8h.html", null ],
    [ "GA.cc", "d5/d06/GA_8cc.html", "d5/d06/GA_8cc" ],
    [ "gauss.cc", "db/d8c/gauss_8cc.html", "db/d8c/gauss_8cc" ],
    [ "gauss.h", "d1/d69/gauss_8h.html", "d1/d69/gauss_8h" ],
    [ "gen_input_structured.cc", "d8/d7d/gen__input__structured_8cc.html", "d8/d7d/gen__input__structured_8cc" ],
    [ "gen_kcdn_syns.cc", "d1/dd5/gen__kcdn__syns_8cc.html", "d1/dd5/gen__kcdn__syns_8cc" ],
    [ "gen_kcdn_syns_fixto10K.cc", "dc/d0a/gen__kcdn__syns__fixto10K_8cc.html", "dc/d0a/gen__kcdn__syns__fixto10K_8cc" ],
    [ "gen_pnkc_syns.cc", "da/d40/gen__pnkc__syns_8cc.html", "da/d40/gen__pnkc__syns_8cc" ],
    [ "gen_pnkc_syns_indivID.cc", "d8/d08/gen__pnkc__syns__indivID_8cc.html", "d8/d08/gen__pnkc__syns__indivID_8cc" ],
    [ "gen_pnlhi_syns.cc", "d2/db6/gen__pnlhi__syns_8cc.html", "d2/db6/gen__pnlhi__syns_8cc" ],
    [ "gen_syns_sparse.cc", "dc/d45/gen__syns__sparse_8cc.html", "dc/d45/gen__syns__sparse_8cc" ],
    [ "gen_syns_sparse_izhModel.cc", "d8/d1e/gen__syns__sparse__izhModel_8cc.html", "d8/d1e/gen__syns__sparse__izhModel_8cc" ],
    [ "HHVclampGA_project/generate_run.cc", "df/d0a/HHVclampGA__project_2generate__run_8cc.html", "df/d0a/HHVclampGA__project_2generate__run_8cc" ],
    [ "Izh_sparse_project/generate_run.cc", "de/de5/Izh__sparse__project_2generate__run_8cc.html", "de/de5/Izh__sparse__project_2generate__run_8cc" ],
    [ "MBody1_project/generate_run.cc", "d7/d00/MBody1__project_2generate__run_8cc.html", "d7/d00/MBody1__project_2generate__run_8cc" ],
    [ "MBody_delayedSyn_project/generate_run.cc", "dc/d39/MBody__delayedSyn__project_2generate__run_8cc.html", "dc/d39/MBody__delayedSyn__project_2generate__run_8cc" ],
    [ "MBody_individualID_project/generate_run.cc", "d6/d29/MBody__individualID__project_2generate__run_8cc.html", "d6/d29/MBody__individualID__project_2generate__run_8cc" ],
    [ "MBody_userdef_project/generate_run.cc", "d6/df9/MBody__userdef__project_2generate__run_8cc.html", "d6/df9/MBody__userdef__project_2generate__run_8cc" ],
    [ "OneComp_project/generate_run.cc", "df/d1c/OneComp__project_2generate__run_8cc.html", "df/d1c/OneComp__project_2generate__run_8cc" ],
    [ "PoissonIzh_project/generate_run.cc", "de/d37/PoissonIzh__project_2generate__run_8cc.html", "de/d37/PoissonIzh__project_2generate__run_8cc" ],
    [ "generateALL.cc", "df/d10/generateALL_8cc.html", "df/d10/generateALL_8cc" ],
    [ "generateALL.h", "d8/deb/generateALL_8h.html", "d8/deb/generateALL_8h" ],
    [ "generateCPU.cc", "da/d80/generateCPU_8cc.html", "da/d80/generateCPU_8cc" ],
    [ "generateCPU.h", "d2/dfd/generateCPU_8h.html", "d2/dfd/generateCPU_8h" ],
    [ "generateKernels.cc", "da/d14/generateKernels_8cc.html", "da/d14/generateKernels_8cc" ],
    [ "generateKernels.h", "d9/d4c/generateKernels_8h.html", "d9/d4c/generateKernels_8h" ],
    [ "generateRunner.cc", "d3/dad/generateRunner_8cc.html", "d3/dad/generateRunner_8cc" ],
    [ "generateRunner.h", "d2/d75/generateRunner_8h.html", "d2/d75/generateRunner_8h" ],
    [ "GeNNHelperKrnls.cu", "db/d69/GeNNHelperKrnls_8cu.html", "db/d69/GeNNHelperKrnls_8cu" ],
    [ "GeNNHelperKrnls.h", "d1/d49/GeNNHelperKrnls_8h.html", "d1/d49/GeNNHelperKrnls_8h" ],
    [ "global.cc", "d7/dd8/global_8cc.html", "d7/dd8/global_8cc" ],
    [ "global.h", "d2/d49/global_8h.html", "d2/d49/global_8h" ],
    [ "helper.h", "d4/da1/helper_8h.html", "d4/da1/helper_8h" ],
    [ "HHVClamp.cc", "d9/dba/HHVClamp_8cc.html", "d9/dba/HHVClamp_8cc" ],
    [ "HHVClampParameters.h", "df/d46/HHVClampParameters_8h.html", "df/d46/HHVClampParameters_8h" ],
    [ "hr_time.cc", "db/dd3/hr__time_8cc.html", "db/dd3/hr__time_8cc" ],
    [ "hr_time.h", "db/dd6/hr__time_8h.html", [
      [ "stopWatch", "d1/df5/structstopWatch.html", "d1/df5/structstopWatch" ],
      [ "CStopWatch", "d9/de8/classCStopWatch.html", "d9/de8/classCStopWatch" ]
    ] ],
    [ "isaac.cc", "dd/d68/isaac_8cc.html", "dd/d68/isaac_8cc" ],
    [ "Izh_sim_sparse.cc", "dd/de6/Izh__sim__sparse_8cc.html", "dd/de6/Izh__sim__sparse_8cc" ],
    [ "Izh_sparse.cc", "d7/d5b/Izh__sparse_8cc.html", "d7/d5b/Izh__sparse_8cc" ],
    [ "Izh_sparse_model.cc", "d3/d43/Izh__sparse__model_8cc.html", "d3/d43/Izh__sparse__model_8cc" ],
    [ "Izh_sparse_model.h", "dd/d4a/Izh__sparse__model_8h.html", [
      [ "classIzh", "de/dba/classclassIzh.html", "de/dba/classclassIzh" ]
    ] ],
    [ "Izh_sparse_sim.h", "df/d0a/Izh__sparse__sim_8h.html", "df/d0a/Izh__sparse__sim_8h" ],
    [ "MBody1_project/model/map_classol.cc", "d9/de1/MBody1__project_2model_2map__classol_8cc.html", "d9/de1/MBody1__project_2model_2map__classol_8cc" ],
    [ "MBody_delayedSyn_project/model/map_classol.cc", "d2/db9/MBody__delayedSyn__project_2model_2map__classol_8cc.html", "d2/db9/MBody__delayedSyn__project_2model_2map__classol_8cc" ],
    [ "MBody_individualID_project/model/map_classol.cc", "dd/d60/MBody__individualID__project_2model_2map__classol_8cc.html", "dd/d60/MBody__individualID__project_2model_2map__classol_8cc" ],
    [ "MBody_userdef_project/model/map_classol.cc", "dd/d6f/MBody__userdef__project_2model_2map__classol_8cc.html", "dd/d6f/MBody__userdef__project_2model_2map__classol_8cc" ],
    [ "MBody1_project/model/map_classol.h", "da/dfc/MBody1__project_2model_2map__classol_8h.html", [
      [ "classol", "d1/d16/classclassol.html", "d1/d16/classclassol" ]
    ] ],
    [ "MBody_delayedSyn_project/model/map_classol.h", "d0/dec/MBody__delayedSyn__project_2model_2map__classol_8h.html", [
      [ "classol", "d1/d16/classclassol.html", "d1/d16/classclassol" ]
    ] ],
    [ "MBody_individualID_project/model/map_classol.h", "d6/d31/MBody__individualID__project_2model_2map__classol_8h.html", [
      [ "classol", "d1/d16/classclassol.html", "d1/d16/classclassol" ]
    ] ],
    [ "MBody_userdef_project/model/map_classol.h", "d1/d8e/MBody__userdef__project_2model_2map__classol_8h.html", [
      [ "classol", "d1/d16/classclassol.html", "d1/d16/classclassol" ]
    ] ],
    [ "HHVclampGA_project/model/MBody1.cc", "de/d16/HHVclampGA__project_2model_2MBody1_8cc.html", "de/d16/HHVclampGA__project_2model_2MBody1_8cc" ],
    [ "MBody1_project/model/MBody1.cc", "dc/de0/MBody1__project_2model_2MBody1_8cc.html", "dc/de0/MBody1__project_2model_2MBody1_8cc" ],
    [ "MBody_delayedSyn.cc", "df/dc6/MBody__delayedSyn_8cc.html", "df/dc6/MBody__delayedSyn_8cc" ],
    [ "MBody_individualID.cc", "d3/d25/MBody__individualID_8cc.html", "d3/d25/MBody__individualID_8cc" ],
    [ "MBody_userdef.cc", "d3/dcd/MBody__userdef_8cc.html", "d3/dcd/MBody__userdef_8cc" ],
    [ "Model_Schmuker_2014_classifier.cc", "d7/d22/Model__Schmuker__2014__classifier_8cc.html", "d7/d22/Model__Schmuker__2014__classifier_8cc" ],
    [ "include/modelSpec.cc", "d9/d6f/include_2modelSpec_8cc.html", null ],
    [ "src/modelSpec.cc", "d8/d9a/src_2modelSpec_8cc.html", "d8/d9a/src_2modelSpec_8cc" ],
    [ "modelSpec.h", "dc/de1/modelSpec_8h.html", "dc/de1/modelSpec_8h" ],
    [ "myModel.cc", "d0/d73/myModel_8cc.html", "d0/d73/myModel_8cc" ],
    [ "neuronModels.cc", "dc/dbc/neuronModels_8cc.html", "dc/dbc/neuronModels_8cc" ],
    [ "neuronModels.h", "d3/dc0/neuronModels_8h.html", "d3/dc0/neuronModels_8h" ],
    [ "OneComp.cc", "db/d47/OneComp_8cc.html", "db/d47/OneComp_8cc" ],
    [ "OneComp_model.cc", "da/de9/OneComp__model_8cc.html", "da/de9/OneComp__model_8cc" ],
    [ "OneComp_model.h", "db/d00/OneComp__model_8h.html", [
      [ "neuronpop", "de/d18/classneuronpop.html", "de/d18/classneuronpop" ]
    ] ],
    [ "OneComp_sim.cc", "d2/d53/OneComp__sim_8cc.html", "d2/d53/OneComp__sim_8cc" ],
    [ "OneComp_sim.h", "dc/d20/OneComp__sim_8h.html", "dc/d20/OneComp__sim_8h" ],
    [ "ov.cc", "d0/db2/ov_8cc.html", "d0/db2/ov_8cc" ],
    [ "parse_options.h", "d7/d44/parse__options_8h.html", "d7/d44/parse__options_8h" ],
    [ "PoissonIzh-model.cc", "d8/d11/PoissonIzh-model_8cc.html", "d8/d11/PoissonIzh-model_8cc" ],
    [ "PoissonIzh-model.h", "df/d16/PoissonIzh-model_8h.html", [
      [ "classol", "d1/d16/classclassol.html", "d1/d16/classclassol" ]
    ] ],
    [ "PoissonIzh.cc", "dc/d3f/PoissonIzh_8cc.html", "dc/d3f/PoissonIzh_8cc" ],
    [ "PoissonIzh_sim.cc", "dd/dfb/PoissonIzh__sim_8cc.html", "dd/dfb/PoissonIzh__sim_8cc" ],
    [ "PoissonIzh_sim.h", "d9/d32/PoissonIzh__sim_8h.html", "d9/d32/PoissonIzh__sim_8h" ],
    [ "postSynapseModels.cc", "d5/d21/postSynapseModels_8cc.html", "d5/d21/postSynapseModels_8cc" ],
    [ "postSynapseModels.h", "d4/d8a/postSynapseModels_8h.html", "d4/d8a/postSynapseModels_8h" ],
    [ "randomGen.cc", "d4/d7d/randomGen_8cc.html", "d4/d7d/randomGen_8cc" ],
    [ "randomGen.h", "de/de8/randomGen_8h.html", "de/de8/randomGen_8h" ],
    [ "Schmuker2014_classifier.cc", "d7/d8d/Schmuker2014__classifier_8cc.html", "d7/d8d/Schmuker2014__classifier_8cc" ],
    [ "Schmuker2014_classifier.h", "dc/d58/Schmuker2014__classifier_8h.html", [
      [ "Schmuker2014_classifier", "d1/dc3/classSchmuker2014__classifier.html", "d1/dc3/classSchmuker2014__classifier" ]
    ] ],
    [ "include/sizes.h", "d2/d8c/include_2sizes_8h.html", "d2/d8c/include_2sizes_8h" ],
    [ "Izh_sparse_project/model/sizes.h", "dc/d68/Izh__sparse__project_2model_2sizes_8h.html", "dc/d68/Izh__sparse__project_2model_2sizes_8h" ],
    [ "MBody1_project/model/sizes.h", "de/ddf/MBody1__project_2model_2sizes_8h.html", "de/ddf/MBody1__project_2model_2sizes_8h" ],
    [ "MBody_delayedSyn_project/model/sizes.h", "dd/df1/MBody__delayedSyn__project_2model_2sizes_8h.html", "dd/df1/MBody__delayedSyn__project_2model_2sizes_8h" ],
    [ "MBody_individualID_project/model/sizes.h", "d0/d8e/MBody__individualID__project_2model_2sizes_8h.html", "d0/d8e/MBody__individualID__project_2model_2sizes_8h" ],
    [ "MBody_userdef_project/model/sizes.h", "d7/d1a/MBody__userdef__project_2model_2sizes_8h.html", "d7/d1a/MBody__userdef__project_2model_2sizes_8h" ],
    [ "OneComp_project/model/sizes.h", "db/d40/OneComp__project_2model_2sizes_8h.html", "db/d40/OneComp__project_2model_2sizes_8h" ],
    [ "PoissonIzh_project/model/sizes.h", "d6/d45/PoissonIzh__project_2model_2sizes_8h.html", "d6/d45/PoissonIzh__project_2model_2sizes_8h" ],
    [ "sparseProjection.h", "d6/d2e/sparseProjection_8h.html", [
      [ "SparseProjection", "d9/d91/structSparseProjection.html", "d9/d91/structSparseProjection" ]
    ] ],
    [ "sparseUtils.cc", "da/d23/sparseUtils_8cc.html", "da/d23/sparseUtils_8cc" ],
    [ "sparseUtils.h", "d8/d69/sparseUtils_8h.html", "d8/d69/sparseUtils_8h" ],
    [ "stringUtils.cc", "dc/db6/stringUtils_8cc.html", "dc/db6/stringUtils_8cc" ],
    [ "stringUtils.h", "dd/dc3/stringUtils_8h.html", "dd/dc3/stringUtils_8h" ],
    [ "synapseModels.cc", "d9/d5b/synapseModels_8cc.html", "d9/d5b/synapseModels_8cc" ],
    [ "synapseModels.h", "d2/d5b/synapseModels_8h.html", "d2/d5b/synapseModels_8h" ],
    [ "emurgano_project/SynDelay.cc", "d5/df0/emurgano__project_2SynDelay_8cc.html", "d5/df0/emurgano__project_2SynDelay_8cc" ],
    [ "SynDelay_project/SynDelay.cc", "de/de0/SynDelay__project_2SynDelay_8cc.html", "de/de0/SynDelay__project_2SynDelay_8cc" ],
    [ "SynDelaySim.cc", "d1/ddf/SynDelaySim_8cc.html", "d1/ddf/SynDelaySim_8cc" ],
    [ "SynDelaySim.cu", "d6/d0d/SynDelaySim_8cu.html", "d6/d0d/SynDelaySim_8cu" ],
    [ "emurgano_project/SynDelaySim.h", "dd/d0d/emurgano__project_2SynDelaySim_8h.html", "dd/d0d/emurgano__project_2SynDelaySim_8h" ],
    [ "SynDelay_project/SynDelaySim.h", "da/d37/SynDelay__project_2SynDelaySim_8h.html", "da/d37/SynDelay__project_2SynDelaySim_8h" ],
    [ "utils.cc", "d7/da9/utils_8cc.html", "d7/da9/utils_8cc" ],
    [ "utils.h", "d5/d60/utils_8h.html", "d5/d60/utils_8h" ],
    [ "VClampGA.cc", "d6/d3f/VClampGA_8cc.html", "d6/d3f/VClampGA_8cc" ],
    [ "VClampGA.h", "d4/de3/VClampGA_8h.html", "d4/de3/VClampGA_8h" ]
];