var files =
[
    [ "MBody1_project/model/classol_sim.cu", "df/d6f/MBody1__project_2model_2classol__sim_8cu.html", "df/d6f/MBody1__project_2model_2classol__sim_8cu" ],
    [ "MBody_delayedSyn_project/model/classol_sim.cu", "dc/d05/MBody__delayedSyn__project_2model_2classol__sim_8cu.html", "dc/d05/MBody__delayedSyn__project_2model_2classol__sim_8cu" ],
    [ "MBody_individualID_project/model/classol_sim.cu", "d8/d4c/MBody__individualID__project_2model_2classol__sim_8cu.html", "d8/d4c/MBody__individualID__project_2model_2classol__sim_8cu" ],
    [ "MBody_userdef_project/model/classol_sim.cu", "d5/d87/MBody__userdef__project_2model_2classol__sim_8cu.html", "d5/d87/MBody__userdef__project_2model_2classol__sim_8cu" ],
    [ "MBody1_project/model/classol_sim.h", "d5/d8d/MBody1__project_2model_2classol__sim_8h.html", "d5/d8d/MBody1__project_2model_2classol__sim_8h" ],
    [ "MBody_delayedSyn_project/model/classol_sim.h", "de/d54/MBody__delayedSyn__project_2model_2classol__sim_8h.html", "de/d54/MBody__delayedSyn__project_2model_2classol__sim_8h" ],
    [ "MBody_individualID_project/model/classol_sim.h", "d1/da6/MBody__individualID__project_2model_2classol__sim_8h.html", "d1/da6/MBody__individualID__project_2model_2classol__sim_8h" ],
    [ "MBody_userdef_project/model/classol_sim.h", "dc/ddd/MBody__userdef__project_2model_2classol__sim_8h.html", "dc/ddd/MBody__userdef__project_2model_2classol__sim_8h" ],
    [ "CodeHelper.cc", "d6/d8a/CodeHelper_8cc.html", "d6/d8a/CodeHelper_8cc" ],
    [ "ensureFtype.h", "d9/d5b/ensureFtype_8h.html", "d9/d5b/ensureFtype_8h" ],
    [ "experiment.cu", "dc/d26/experiment_8cu.html", "dc/d26/experiment_8cu" ],
    [ "experiment.h", "dc/d02/experiment_8h.html", "dc/d02/experiment_8h" ],
    [ "extra_neurons.h", "db/d66/extra__neurons_8h.html", "db/d66/extra__neurons_8h" ],
    [ "lib/include/extra_postsynapses.h", "d1/de9/lib_2include_2extra__postsynapses_8h.html", "d1/de9/lib_2include_2extra__postsynapses_8h" ],
    [ "SpineML_to_GeNN/extra_postsynapses.h", "d9/d1d/SpineML__to__GeNN_2extra__postsynapses_8h.html", "d9/d1d/SpineML__to__GeNN_2extra__postsynapses_8h" ],
    [ "extra_weightupdates.h", "d4/d71/extra__weightupdates_8h.html", null ],
    [ "GA.cc", "d5/d06/GA_8cc.html", "d5/d06/GA_8cc" ],
    [ "gauss.cc", "db/d8c/gauss_8cc.html", "db/d8c/gauss_8cc" ],
    [ "gauss.h", "d1/d69/gauss_8h.html", "d1/d69/gauss_8h" ],
    [ "gen_input_structured.cc", "d8/d7d/gen__input__structured_8cc.html", "d8/d7d/gen__input__structured_8cc" ],
    [ "gen_kcdn_syns.cc", "d1/dd5/gen__kcdn__syns_8cc.html", "d1/dd5/gen__kcdn__syns_8cc" ],
    [ "gen_kcdn_syns_fixto10K.cc", "dc/d0a/gen__kcdn__syns__fixto10K_8cc.html", "dc/d0a/gen__kcdn__syns__fixto10K_8cc" ],
    [ "gen_pnkc_syns.cc", "da/d40/gen__pnkc__syns_8cc.html", "da/d40/gen__pnkc__syns_8cc" ],
    [ "gen_pnkc_syns_indivID.cc", "d8/d08/gen__pnkc__syns__indivID_8cc.html", "d8/d08/gen__pnkc__syns__indivID_8cc" ],
    [ "gen_pnlhi_syns.cc", "d2/db6/gen__pnlhi__syns_8cc.html", "d2/db6/gen__pnlhi__syns_8cc" ],
    [ "gen_syns_sparse.cc", "dc/d45/gen__syns__sparse_8cc.html", "dc/d45/gen__syns__sparse_8cc" ],
    [ "gen_syns_sparse_izhModel.cc", "d8/d1e/gen__syns__sparse__izhModel_8cc.html", "d8/d1e/gen__syns__sparse__izhModel_8cc" ],
    [ "HHVclampGA_project/generate_run.cc", "df/d0a/HHVclampGA__project_2generate__run_8cc.html", "df/d0a/HHVclampGA__project_2generate__run_8cc" ],
    [ "Izh_sparse_project/generate_run.cc", "de/de5/Izh__sparse__project_2generate__run_8cc.html", "de/de5/Izh__sparse__project_2generate__run_8cc" ],
    [ "MBody1_project/generate_run.cc", "d7/d00/MBody1__project_2generate__run_8cc.html", "d7/d00/MBody1__project_2generate__run_8cc" ],
    [ "MBody_delayedSyn_project/generate_run.cc", "dc/d39/MBody__delayedSyn__project_2generate__run_8cc.html", "dc/d39/MBody__delayedSyn__project_2generate__run_8cc" ],
    [ "MBody_individualID_project/generate_run.cc", "d6/d29/MBody__individualID__project_2generate__run_8cc.html", "d6/d29/MBody__individualID__project_2generate__run_8cc" ],
    [ "MBody_userdef_project/generate_run.cc", "d6/df9/MBody__userdef__project_2generate__run_8cc.html", "d6/df9/MBody__userdef__project_2generate__run_8cc" ],
    [ "OneComp_project/generate_run.cc", "df/d1c/OneComp__project_2generate__run_8cc.html", "df/d1c/OneComp__project_2generate__run_8cc" ],
    [ "PoissonIzh_project/generate_run.cc", "de/d37/PoissonIzh__project_2generate__run_8cc.html", "de/d37/PoissonIzh__project_2generate__run_8cc" ],
    [ "generateALL.cc", "df/d10/generateALL_8cc.html", "df/d10/generateALL_8cc" ],
    [ "generateCPU.cc", "da/d80/generateCPU_8cc.html", "da/d80/generateCPU_8cc" ],
    [ "generateKernels.cc", "da/d14/generateKernels_8cc.html", "da/d14/generateKernels_8cc" ],
    [ "generateRunner.cc", "d3/dad/generateRunner_8cc.html", "d3/dad/generateRunner_8cc" ],
    [ "GeNNHelperKrnls.cu", "db/d69/GeNNHelperKrnls_8cu.html", "db/d69/GeNNHelperKrnls_8cu" ],
    [ "global.h", "d2/d49/global_8h.html", "d2/d49/global_8h" ],
    [ "helper.h", "d4/da1/helper_8h.html", "d4/da1/helper_8h" ],
    [ "HHVClamp.cc", "d9/dba/HHVClamp_8cc.html", "d9/dba/HHVClamp_8cc" ],
    [ "hr_time.cpp", "df/d71/hr__time_8cpp.html", "df/d71/hr__time_8cpp" ],
    [ "hr_time.h", "db/dd6/hr__time_8h.html", [
      [ "stopWatch", "d1/df5/structstopWatch.html", "d1/df5/structstopWatch" ],
      [ "CStopWatch", "d9/de8/classCStopWatch.html", "d9/de8/classCStopWatch" ]
    ] ],
    [ "Izh_sim_sparse.cu", "da/dab/Izh__sim__sparse_8cu.html", "da/dab/Izh__sim__sparse_8cu" ],
    [ "Izh_sparse.cc", "d7/d5b/Izh__sparse_8cc.html", "d7/d5b/Izh__sparse_8cc" ],
    [ "Izh_sparse_model.cc", "d3/d43/Izh__sparse__model_8cc.html", "d3/d43/Izh__sparse__model_8cc" ],
    [ "Izh_sparse_model.h", "dd/d4a/Izh__sparse__model_8h.html", [
      [ "classIzh", "de/dba/classclassIzh.html", "de/dba/classclassIzh" ]
    ] ],
    [ "Izh_sparse_sim.h", "df/d0a/Izh__sparse__sim_8h.html", "df/d0a/Izh__sparse__sim_8h" ],
    [ "MBody1_project/model/map_classol.cc", "d9/de1/MBody1__project_2model_2map__classol_8cc.html", "d9/de1/MBody1__project_2model_2map__classol_8cc" ],
    [ "MBody_delayedSyn_project/model/map_classol.cc", "d2/db9/MBody__delayedSyn__project_2model_2map__classol_8cc.html", "d2/db9/MBody__delayedSyn__project_2model_2map__classol_8cc" ],
    [ "MBody_individualID_project/model/map_classol.cc", "dd/d60/MBody__individualID__project_2model_2map__classol_8cc.html", "dd/d60/MBody__individualID__project_2model_2map__classol_8cc" ],
    [ "MBody_userdef_project/model/map_classol.cc", "dd/d6f/MBody__userdef__project_2model_2map__classol_8cc.html", "dd/d6f/MBody__userdef__project_2model_2map__classol_8cc" ],
    [ "MBody1_project/model/map_classol.h", "da/dfc/MBody1__project_2model_2map__classol_8h.html", [
      [ "classol", "d1/d16/classclassol.html", "d1/d16/classclassol" ]
    ] ],
    [ "MBody_delayedSyn_project/model/map_classol.h", "d0/dec/MBody__delayedSyn__project_2model_2map__classol_8h.html", [
      [ "classol", "d1/d16/classclassol.html", "d1/d16/classclassol" ]
    ] ],
    [ "MBody_individualID_project/model/map_classol.h", "d6/d31/MBody__individualID__project_2model_2map__classol_8h.html", [
      [ "classol", "d1/d16/classclassol.html", "d1/d16/classclassol" ]
    ] ],
    [ "MBody_userdef_project/model/map_classol.h", "d1/d8e/MBody__userdef__project_2model_2map__classol_8h.html", [
      [ "classol", "d1/d16/classclassol.html", "d1/d16/classclassol" ]
    ] ],
    [ "HHVclampGA_project/model/MBody1.cc", "de/d16/HHVclampGA__project_2model_2MBody1_8cc.html", "de/d16/HHVclampGA__project_2model_2MBody1_8cc" ],
    [ "MBody1_project/model/MBody1.cc", "dc/de0/MBody1__project_2model_2MBody1_8cc.html", "dc/de0/MBody1__project_2model_2MBody1_8cc" ],
    [ "MBody_delayedSyn.cc", "df/dc6/MBody__delayedSyn_8cc.html", "df/dc6/MBody__delayedSyn_8cc" ],
    [ "MBody_individualID.cc", "d3/d25/MBody__individualID_8cc.html", "d3/d25/MBody__individualID_8cc" ],
    [ "featureTests/supportCode/MBody_userdef.cc", "d2/d9f/featureTests_2supportCode_2MBody__userdef_8cc.html", "d2/d9f/featureTests_2supportCode_2MBody__userdef_8cc" ],
    [ "userproject/MBody_userdef_project/model/MBody_userdef.cc", "de/d1c/userproject_2MBody__userdef__project_2model_2MBody__userdef_8cc.html", "de/d1c/userproject_2MBody__userdef__project_2model_2MBody__userdef_8cc" ],
    [ "Model_Schmuker_2014_classifier.cc", "d7/d22/Model__Schmuker__2014__classifier_8cc.html", "d7/d22/Model__Schmuker__2014__classifier_8cc" ],
    [ "modelSpec.cc", "d7/dfd/modelSpec_8cc.html", "d7/dfd/modelSpec_8cc" ],
    [ "modelSpec.h", "dc/de1/modelSpec_8h.html", "dc/de1/modelSpec_8h" ],
    [ "OneComp.cc", "db/d47/OneComp_8cc.html", "db/d47/OneComp_8cc" ],
    [ "OneComp_model.cc", "da/de9/OneComp__model_8cc.html", "da/de9/OneComp__model_8cc" ],
    [ "OneComp_model.h", "db/d00/OneComp__model_8h.html", [
      [ "neuronpop", "de/d18/classneuronpop.html", "de/d18/classneuronpop" ]
    ] ],
    [ "OneComp_sim.cu", "d3/de7/OneComp__sim_8cu.html", "d3/de7/OneComp__sim_8cu" ],
    [ "OneComp_sim.h", "dc/d20/OneComp__sim_8h.html", "dc/d20/OneComp__sim_8h" ],
    [ "PoissonIzh-model.cc", "d8/d11/PoissonIzh-model_8cc.html", "d8/d11/PoissonIzh-model_8cc" ],
    [ "PoissonIzh-model.h", "df/d16/PoissonIzh-model_8h.html", [
      [ "classol", "d1/d16/classclassol.html", "d1/d16/classclassol" ]
    ] ],
    [ "PoissonIzh.cc", "dc/d3f/PoissonIzh_8cc.html", "dc/d3f/PoissonIzh_8cc" ],
    [ "PoissonIzh_sim.cu", "d3/d43/PoissonIzh__sim_8cu.html", "d3/d43/PoissonIzh__sim_8cu" ],
    [ "PoissonIzh_sim.h", "d9/d32/PoissonIzh__sim_8h.html", "d9/d32/PoissonIzh__sim_8h" ],
    [ "postVarsInPostLearn.cc", "db/d0a/postVarsInPostLearn_8cc.html", "db/d0a/postVarsInPostLearn_8cc" ],
    [ "postVarsInPostLearn_sparse.cc", "d1/d13/postVarsInPostLearn__sparse_8cc.html", "d1/d13/postVarsInPostLearn__sparse_8cc" ],
    [ "postVarsInSimCode.cc", "de/d35/postVarsInSimCode_8cc.html", "de/d35/postVarsInSimCode_8cc" ],
    [ "postVarsInSimCode_sparse.cc", "d3/dad/postVarsInSimCode__sparse_8cc.html", "d3/dad/postVarsInSimCode__sparse_8cc" ],
    [ "postVarsInSynapseDynamics.cc", "d2/d27/postVarsInSynapseDynamics_8cc.html", "d2/d27/postVarsInSynapseDynamics_8cc" ],
    [ "postVarsInSynapseDynamics_sparse.cc", "d6/d1f/postVarsInSynapseDynamics__sparse_8cc.html", "d6/d1f/postVarsInSynapseDynamics__sparse_8cc" ],
    [ "preVarsInPostLearn.cc", "d0/dd7/preVarsInPostLearn_8cc.html", "d0/dd7/preVarsInPostLearn_8cc" ],
    [ "preVarsInPostLearn_sparse.cc", "d9/d09/preVarsInPostLearn__sparse_8cc.html", "d9/d09/preVarsInPostLearn__sparse_8cc" ],
    [ "preVarsInSimCode.cc", "dd/db2/preVarsInSimCode_8cc.html", "dd/db2/preVarsInSimCode_8cc" ],
    [ "preVarsInSimCode_sparse.cc", "de/d7d/preVarsInSimCode__sparse_8cc.html", "de/d7d/preVarsInSimCode__sparse_8cc" ],
    [ "preVarsInSynapseDynamics.cc", "d4/d49/preVarsInSynapseDynamics_8cc.html", "d4/d49/preVarsInSynapseDynamics_8cc" ],
    [ "preVarsInSynapseDynamics_sparse.cc", "df/d0e/preVarsInSynapseDynamics__sparse_8cc.html", "df/d0e/preVarsInSynapseDynamics__sparse_8cc" ],
    [ "randomGen.cc", "d4/d7d/randomGen_8cc.html", "d4/d7d/randomGen_8cc" ],
    [ "randomGen.h", "de/de8/randomGen_8h.html", "de/de8/randomGen_8h" ],
    [ "Schmuker2014_classifier.cu", "d0/db2/Schmuker2014__classifier_8cu.html", "d0/db2/Schmuker2014__classifier_8cu" ],
    [ "Schmuker2014_classifier.h", "dc/d58/Schmuker2014__classifier_8h.html", [
      [ "Schmuker2014_classifier", "d1/dc3/classSchmuker2014__classifier.html", "d1/dc3/classSchmuker2014__classifier" ]
    ] ],
    [ "simpleBit.h", "db/d06/simpleBit_8h.html", "db/d06/simpleBit_8h" ],
    [ "sizes.h", "d4/deb/sizes_8h.html", "d4/deb/sizes_8h" ],
    [ "sparseUtils.cc", "da/d23/sparseUtils_8cc.html", "da/d23/sparseUtils_8cc" ],
    [ "stringutils.h", "d9/d9e/stringutils_8h.html", "d9/d9e/stringutils_8h" ],
    [ "SynDelay.cc", "dd/d0e/SynDelay_8cc.html", "dd/d0e/SynDelay_8cc" ],
    [ "SynDelaySim.cu", "d6/d0d/SynDelaySim_8cu.html", "d6/d0d/SynDelaySim_8cu" ],
    [ "SynDelaySim.h", "db/df9/SynDelaySim_8h.html", "db/df9/SynDelaySim_8h" ],
    [ "testDefaultContructor.cu", "dd/d68/testDefaultContructor_8cu.html", "dd/d68/testDefaultContructor_8cu" ],
    [ "postsynapticVariables/testHelper.h", "db/de3/postsynapticVariables_2testHelper_8h.html", "db/de3/postsynapticVariables_2testHelper_8h" ],
    [ "presynapticVariables/testHelper.h", "d7/dce/presynapticVariables_2testHelper_8h.html", "d7/dce/presynapticVariables_2testHelper_8h" ],
    [ "testMixedArray.cc", "df/d33/testMixedArray_8cc.html", "df/d33/testMixedArray_8cc" ],
    [ "testPostVarsInPostLearn.cu", "db/d8a/testPostVarsInPostLearn_8cu.html", "db/d8a/testPostVarsInPostLearn_8cu" ],
    [ "testPostVarsInPostLearn.h", "d3/da9/testPostVarsInPostLearn_8h.html", "d3/da9/testPostVarsInPostLearn_8h" ],
    [ "testPostVarsInPostLearn_sparse.cu", "dd/de9/testPostVarsInPostLearn__sparse_8cu.html", "dd/de9/testPostVarsInPostLearn__sparse_8cu" ],
    [ "testPostVarsInPostLearn_sparse.h", "dc/d6f/testPostVarsInPostLearn__sparse_8h.html", "dc/d6f/testPostVarsInPostLearn__sparse_8h" ],
    [ "testPostVarsInSimCode.cu", "d9/d18/testPostVarsInSimCode_8cu.html", "d9/d18/testPostVarsInSimCode_8cu" ],
    [ "testPostVarsInSimCode.h", "de/df6/testPostVarsInSimCode_8h.html", "de/df6/testPostVarsInSimCode_8h" ],
    [ "testPostVarsInSimCode_sparse.cu", "d5/d8b/testPostVarsInSimCode__sparse_8cu.html", "d5/d8b/testPostVarsInSimCode__sparse_8cu" ],
    [ "testPostVarsInSimCode_sparse.h", "d5/d6f/testPostVarsInSimCode__sparse_8h.html", "d5/d6f/testPostVarsInSimCode__sparse_8h" ],
    [ "testPostVarsInSynapseDynamics.cu", "de/df1/testPostVarsInSynapseDynamics_8cu.html", "de/df1/testPostVarsInSynapseDynamics_8cu" ],
    [ "testPostVarsInSynapseDynamics.h", "d1/d4d/testPostVarsInSynapseDynamics_8h.html", "d1/d4d/testPostVarsInSynapseDynamics_8h" ],
    [ "testPostVarsInSynapseDynamics_sparse.cu", "d7/dcc/testPostVarsInSynapseDynamics__sparse_8cu.html", "d7/dcc/testPostVarsInSynapseDynamics__sparse_8cu" ],
    [ "testPostVarsInSynapseDynamics_sparse.h", "d0/d7a/testPostVarsInSynapseDynamics__sparse_8h.html", "d0/d7a/testPostVarsInSynapseDynamics__sparse_8h" ],
    [ "testPreVarsInPostLearn.cu", "db/d0f/testPreVarsInPostLearn_8cu.html", "db/d0f/testPreVarsInPostLearn_8cu" ],
    [ "testPreVarsInPostLearn.h", "d3/de5/testPreVarsInPostLearn_8h.html", "d3/de5/testPreVarsInPostLearn_8h" ],
    [ "testPreVarsInPostLearn_sparse.cu", "d7/d56/testPreVarsInPostLearn__sparse_8cu.html", "d7/d56/testPreVarsInPostLearn__sparse_8cu" ],
    [ "testPreVarsInPostLearn_sparse.h", "d2/d2a/testPreVarsInPostLearn__sparse_8h.html", "d2/d2a/testPreVarsInPostLearn__sparse_8h" ],
    [ "testPreVarsInSimCode.cu", "d5/d63/testPreVarsInSimCode_8cu.html", "d5/d63/testPreVarsInSimCode_8cu" ],
    [ "testPreVarsInSimCode.h", "de/dd3/testPreVarsInSimCode_8h.html", "de/dd3/testPreVarsInSimCode_8h" ],
    [ "testPreVarsInSimCode_sparse.cu", "d5/d5d/testPreVarsInSimCode__sparse_8cu.html", "d5/d5d/testPreVarsInSimCode__sparse_8cu" ],
    [ "testPreVarsInSimCode_sparse.h", "d5/db8/testPreVarsInSimCode__sparse_8h.html", "d5/db8/testPreVarsInSimCode__sparse_8h" ],
    [ "testPreVarsInSynapseDynamics.cu", "d4/d26/testPreVarsInSynapseDynamics_8cu.html", "d4/d26/testPreVarsInSynapseDynamics_8cu" ],
    [ "testPreVarsInSynapseDynamics.h", "d2/d90/testPreVarsInSynapseDynamics_8h.html", "d2/d90/testPreVarsInSynapseDynamics_8h" ],
    [ "testPreVarsInSynapseDynamics_sparse.cu", "d4/da8/testPreVarsInSynapseDynamics__sparse_8cu.html", "d4/da8/testPreVarsInSynapseDynamics__sparse_8cu" ],
    [ "testPreVarsInSynapseDynamics_sparse.h", "d4/d70/testPreVarsInSynapseDynamics__sparse_8h.html", "d4/d70/testPreVarsInSynapseDynamics__sparse_8h" ],
    [ "testRegEx.cc", "d0/d36/testRegEx_8cc.html", "d0/d36/testRegEx_8cc" ],
    [ "toString.h", "dd/d28/toString_8h.html", "dd/d28/toString_8h" ],
    [ "utils.h", "d5/d60/utils_8h.html", "d5/d60/utils_8h" ],
    [ "VClampGA.cu", "d1/d20/VClampGA_8cu.html", "d1/d20/VClampGA_8cu" ],
    [ "VClampGA.h", "d4/de3/VClampGA_8h.html", "d4/de3/VClampGA_8h" ]
];