var hierarchy =
[
    [ "classIzh", "de/dba/classclassIzh.html", null ],
    [ "classol", "d1/d16/classclassol.html", null ],
    [ "CodeHelper", "d1/d03/classCodeHelper.html", null ],
    [ "CStopWatch", "d9/de8/classCStopWatch.html", null ],
    [ "dpclass", "db/de6/classdpclass.html", [
      [ "expDecayDp", "da/d0d/classexpDecayDp.html", null ],
      [ "pwSTDP", "d0/dba/classpwSTDP.html", null ],
      [ "pwSTDP_userdef", "dd/d4e/classpwSTDP__userdef.html", null ],
      [ "pwSTDP_userdef", "dd/d4e/classpwSTDP__userdef.html", null ],
      [ "rulkovdp", "d6/d9e/classrulkovdp.html", null ]
    ] ],
    [ "errTupel", "d4/da7/structerrTupel.html", null ],
    [ "inputSpec", "de/dad/structinputSpec.html", null ],
    [ "neuronModel", "d3/d64/structneuronModel.html", null ],
    [ "neuronpop", "de/d18/classneuronpop.html", null ],
    [ "NNmodel", "dc/de5/classNNmodel.html", null ],
    [ "Parameter", "d9/d00/structParameter.html", null ],
    [ "postSynModel", "d8/dbb/structpostSynModel.html", null ],
    [ "postVarsInPostLearn", "dd/df9/classpostVarsInPostLearn.html", null ],
    [ "postVarsInPostLearn_sparse", "d3/d3e/classpostVarsInPostLearn__sparse.html", null ],
    [ "postVarsInSimCode", "d9/d04/classpostVarsInSimCode.html", null ],
    [ "postVarsInSimCode_sparse", "d7/d09/classpostVarsInSimCode__sparse.html", null ],
    [ "postVarsInSynapseDynamics", "d0/d21/classpostVarsInSynapseDynamics.html", null ],
    [ "postVarsInSynapseDynamics_sparse", "de/dd4/classpostVarsInSynapseDynamics__sparse.html", null ],
    [ "preVarsInPostLearn", "dc/d93/classpreVarsInPostLearn.html", null ],
    [ "preVarsInPostLearn_sparse", "db/da4/classpreVarsInPostLearn__sparse.html", null ],
    [ "preVarsInSimCode", "d1/dc2/classpreVarsInSimCode.html", null ],
    [ "preVarsInSimCode_sparse", "de/d14/classpreVarsInSimCode__sparse.html", null ],
    [ "preVarsInSynapseDynamics", "d4/d6b/classpreVarsInSynapseDynamics.html", null ],
    [ "preVarsInSynapseDynamics_sparse", "d3/d88/classpreVarsInSynapseDynamics__sparse.html", null ],
    [ "randomGauss", "d5/d45/classrandomGauss.html", null ],
    [ "randomGen", "d8/d3b/classrandomGen.html", null ],
    [ "Schmuker2014_classifier", "d1/dc3/classSchmuker2014__classifier.html", null ],
    [ "stdRG", "db/d09/classstdRG.html", null ],
    [ "stopWatch", "d1/df5/structstopWatch.html", null ],
    [ "SynDelay", "db/df7/classSynDelay.html", null ],
    [ "weightUpdateModel", "dd/db7/classweightUpdateModel.html", null ]
];