##--------------------------------------------------------------------------
##   Author: Alan Diamond
##  
##   Institute: Center for Computational Neuroscience and Robotics
##              University of Sussex
##            Falmer, Brighton BN1 9QJ, UK 
##  
##  
##--------------------------------------------------------------------------

EXECUTABLE	:= experiment
SOURCES		:= experiment.cu
OPTIMIZATIONFLAGS:= -O3

include	$(GENN_PATH)/userproject/include/makefile_common_gnu.mk
