##--------------------------------------------------------------------------
##   Author: Alan Diamond
##  
##   Institute: Center for Computational Neuroscience and Robotics
##              University of Sussex
##            Falmer, Brighton BN1 9QJ, UK 
##  
##  
##--------------------------------------------------------------------------

ROOTDIR		:= $(GeNNPATH)/userproject/Model_Schmuker_2014_classifier_project
EXECUTABLE	:= experiment
SOURCES		:= experiment.cu

INCLUDE_FLAGS	:= 
LINK_FLAGS	:= 
CCFLAGS		:= 
NVCCFLAGS	:= 

ifdef COMSPEC
	include	$(GeNNPATH)/lib/include/makefile_common_cygwin.mk
else
	include	$(GeNNPATH)/lib/include/makefile_common.mk
endif
