# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_Snippet')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_Snippet')
    _Snippet = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Snippet', [dirname(__file__)])
        except ImportError:
            import _Snippet
            return _Snippet
        try:
            _mod = imp.load_module('_Snippet', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _Snippet = swig_import_helper()
    del swig_import_helper
else:
    import _Snippet
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

try:
    import weakref
    weakref_proxy = weakref.proxy
except __builtin__.Exception:
    weakref_proxy = lambda x: x


from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    from . import StlContainers
else:
    import StlContainers
del _swig_python_version_info
class Base(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Base, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Base, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _Snippet.delete_Base
    __del__ = lambda self: None

    def get_param_names(self) -> "Snippet::Base::StringVec":
        return _Snippet.Base_get_param_names(self)

    def get_derived_params(self) -> "Snippet::Base::DerivedParamVec":
        return _Snippet.Base_get_derived_params(self)

    def __init__(self):
        if self.__class__ == Base:
            _self = None
        else:
            _self = self
        this = _Snippet.new_Base(_self, )
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    def __disown__(self):
        self.this.disown()
        _Snippet.disown_Base(self)
        return weakref_proxy(self)
Base_swigregister = _Snippet.Base_swigregister
Base_swigregister(Base)

class DerivedParamFunc(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DerivedParamFunc, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DerivedParamFunc, name)
    __repr__ = _swig_repr

    def __call__(self, pars: 'DoubleVector', dt: 'double') -> "double":
        return _Snippet.DerivedParamFunc___call__(self, pars, dt)
    __swig_destroy__ = _Snippet.delete_DerivedParamFunc
    __del__ = lambda self: None

    def __init__(self):
        if self.__class__ == DerivedParamFunc:
            _self = None
        else:
            _self = self
        this = _Snippet.new_DerivedParamFunc(_self, )
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    def __disown__(self):
        self.this.disown()
        _Snippet.disown_DerivedParamFunc(self)
        return weakref_proxy(self)
DerivedParamFunc_swigregister = _Snippet.DerivedParamFunc_swigregister
DerivedParamFunc_swigregister(DerivedParamFunc)


def make_dpf(dpf: 'DerivedParamFunc') -> "std::function< double (std::vector< double,std::allocator< double > > const &,double) >":
    return _Snippet.make_dpf(dpf)
make_dpf = _Snippet.make_dpf
# This file is compatible with both classic and new-style classes.


