##--------------------------------------------------------------------------
##   Author: James Turner
##  
##   Institute: Center for Computational Neuroscience and Robotics
##              University of Sussex
##              Falmer, Brighton BN1 9QJ, UK 
##  
##   email to:  J.P.Turner@sussex.ac.uk
##  
##--------------------------------------------------------------------------

EXECUTABLE		:=syn_delay
SOURCES			:=SynDelaySim.cu
OPTIMIZATIONFLAGS	:=-O3

include	$(GENN_PATH)/userproject/include/makefile_common_gnu.mk
