##--------------------------------------------------------------------------
##   Author: Thomas Nowotny
##  
##   Institute: Center for Computational Neuroscience and Robotics
##              University of Sussex
##            Falmer, Brighton BN1 9QJ, UK 
##  
##   email to:  T.Nowotny@sussex.ac.uk
##  
##   initial version: 2010-02-07
##  
##--------------------------------------------------------------------------

ROOTDIR		:= $(GeNNPATH)/userproject/SynDelay_project
EXECUTABLE	:= syn_delay
SOURCES		:= SynDelaySim.cu

INCLUDE_FLAGS	:= 
LINK_FLAGS	:= 
CCFLAGS		:= 
NVCCFLAGS	:= 

ifdef COMSPEC
	include	$(GeNNPATH)/userproject/include/makefile_common_win.mk
else
	include	$(GeNNPATH)/userproject/include/makefile_common_gnu.mk
endif
