var annotated_dup =
[
    [ "CurrentSourceModels", "d6/dd3/namespaceCurrentSourceModels.html", "d6/dd3/namespaceCurrentSourceModels" ],
    [ "generate_swig_interfaces", "d9/d94/namespacegenerate__swig__interfaces.html", "d9/d94/namespacegenerate__swig__interfaces" ],
    [ "InitSparseConnectivitySnippet", "dc/ddd/namespaceInitSparseConnectivitySnippet.html", "dc/ddd/namespaceInitSparseConnectivitySnippet" ],
    [ "InitVarSnippet", "d2/dfc/namespaceInitVarSnippet.html", "d2/dfc/namespaceInitVarSnippet" ],
    [ "NeuronModels", "da/dac/namespaceNeuronModels.html", "da/dac/namespaceNeuronModels" ],
    [ "NewModels", "d2/d9d/namespaceNewModels.html", "d2/d9d/namespaceNewModels" ],
    [ "PostsynapticModels", "db/dcb/namespacePostsynapticModels.html", "db/dcb/namespacePostsynapticModels" ],
    [ "pygenn", "da/d6d/namespacepygenn.html", "da/d6d/namespacepygenn" ],
    [ "Snippet", "df/daa/namespaceSnippet.html", "df/daa/namespaceSnippet" ],
    [ "WeightUpdateModels", "da/d80/namespaceWeightUpdateModels.html", "da/d80/namespaceWeightUpdateModels" ],
    [ "CodeStream", "da/da8/classCodeStream.html", "da/da8/classCodeStream" ],
    [ "CStopWatch", "d9/de8/classCStopWatch.html", "d9/de8/classCStopWatch" ],
    [ "CurrentSource", "d1/d48/classCurrentSource.html", "d1/d48/classCurrentSource" ],
    [ "dpclass", "db/de6/classdpclass.html", "db/de6/classdpclass" ],
    [ "expDecayDp", "da/d0d/classexpDecayDp.html", "da/d0d/classexpDecayDp" ],
    [ "FunctionTemplate", "d4/da7/structFunctionTemplate.html", "d4/da7/structFunctionTemplate" ],
    [ "GenericFunction", "d3/da1/structGenericFunction.html", "d3/da1/structGenericFunction" ],
    [ "NameIterCtx", "d0/d76/structNameIterCtx.html", "d0/d76/structNameIterCtx" ],
    [ "NeuronGroup", "d7/d3b/classNeuronGroup.html", "d7/d3b/classNeuronGroup" ],
    [ "neuronModel", "d3/dc9/classneuronModel.html", "d3/dc9/classneuronModel" ],
    [ "NNmodel", "dc/de5/classNNmodel.html", "dc/de5/classNNmodel" ],
    [ "PairKeyConstIter", "d2/dab/classPairKeyConstIter.html", "d2/dab/classPairKeyConstIter" ],
    [ "postSynModel", "d2/d1a/classpostSynModel.html", "d2/d1a/classpostSynModel" ],
    [ "pwSTDP", "d0/dba/classpwSTDP.html", "d0/dba/classpwSTDP" ],
    [ "RaggedProjection", "d2/d75/structRaggedProjection.html", "d2/d75/structRaggedProjection" ],
    [ "rulkovdp", "d6/d9e/classrulkovdp.html", "d6/d9e/classrulkovdp" ],
    [ "SparseProjection", "d9/d91/structSparseProjection.html", "d9/d91/structSparseProjection" ],
    [ "stopWatch", "d1/df5/structstopWatch.html", "d1/df5/structstopWatch" ],
    [ "SynapseGroup", "dc/dfa/classSynapseGroup.html", "dc/dfa/classSynapseGroup" ],
    [ "weightUpdateModel", "dd/db7/classweightUpdateModel.html", "dd/db7/classweightUpdateModel" ]
];