var files =
[
    [ "build/lib.linux-x86_64-3.6/pygenn/__init__.py", "df/d1e/build_2lib_8linux-x86__64-3_86_2pygenn_2____init_____8py.html", null ],
    [ "build/lib.linux-x86_64-3.6/pygenn/genn_wrapper/__init__.py", "db/d30/build_2lib_8linux-x86__64-3_86_2pygenn_2genn__wrapper_2____init_____8py.html", null ],
    [ "pygenn/__init__.py", "d1/d63/pygenn_2____init_____8py.html", null ],
    [ "binomial.cc", "d6/d24/binomial_8cc.html", "d6/d24/binomial_8cc" ],
    [ "binomial.h", "d4/d59/binomial_8h.html", "d4/d59/binomial_8h" ],
    [ "codeGenUtils.cc", "d4/dba/codeGenUtils_8cc.html", "d4/dba/codeGenUtils_8cc" ],
    [ "codeGenUtils.h", "de/d99/codeGenUtils_8h.html", "de/d99/codeGenUtils_8h" ],
    [ "codeStream.cc", "db/dfd/codeStream_8cc.html", "db/dfd/codeStream_8cc" ],
    [ "codeStream.h", "d0/dbb/codeStream_8h.html", "d0/dbb/codeStream_8h" ],
    [ "CUDABackend.py", "df/d50/CUDABackend_8py.html", "df/d50/CUDABackend_8py" ],
    [ "currentSource.cc", "d7/d8c/currentSource_8cc.html", null ],
    [ "currentSource.h", "da/db7/currentSource_8h.html", [
      [ "CurrentSource", "d1/d48/classCurrentSource.html", "d1/d48/classCurrentSource" ]
    ] ],
    [ "currentSourceModels.cc", "d4/d8a/currentSourceModels_8cc.html", "d4/d8a/currentSourceModels_8cc" ],
    [ "currentSourceModels.h", "da/d49/currentSourceModels_8h.html", "da/d49/currentSourceModels_8h" ],
    [ "CurrentSourceModels.py", "dd/de3/CurrentSourceModels_8py.html", "dd/de3/CurrentSourceModels_8py" ],
    [ "dpclass.h", "da/dc8/dpclass_8h.html", [
      [ "dpclass", "db/de6/classdpclass.html", "db/de6/classdpclass" ]
    ] ],
    [ "extra_neurons.h", "db/d66/extra__neurons_8h.html", "db/d66/extra__neurons_8h" ],
    [ "extra_postsynapses.h", "d5/d73/extra__postsynapses_8h.html", "d5/d73/extra__postsynapses_8h" ],
    [ "extra_weightupdates.h", "d4/d71/extra__weightupdates_8h.html", null ],
    [ "generate_swig_interfaces.py", "d1/d25/generate__swig__interfaces_8py.html", "d1/d25/generate__swig__interfaces_8py" ],
    [ "generateALL.cc", "df/d10/generateALL_8cc.html", "df/d10/generateALL_8cc" ],
    [ "generateALL.h", "d8/deb/generateALL_8h.html", "d8/deb/generateALL_8h" ],
    [ "generateCPU.cc", "da/d80/generateCPU_8cc.html", "da/d80/generateCPU_8cc" ],
    [ "generateCPU.h", "d2/dfd/generateCPU_8h.html", "d2/dfd/generateCPU_8h" ],
    [ "generateInit.cc", "d7/dac/generateInit_8cc.html", "d7/dac/generateInit_8cc" ],
    [ "generateInit.h", "d7/d53/generateInit_8h.html", "d7/d53/generateInit_8h" ],
    [ "generateKernels.cc", "da/d14/generateKernels_8cc.html", "da/d14/generateKernels_8cc" ],
    [ "generateKernels.h", "d9/d4c/generateKernels_8h.html", "d9/d4c/generateKernels_8h" ],
    [ "generateMPI.cc", "da/d2c/generateMPI_8cc.html", "da/d2c/generateMPI_8cc" ],
    [ "generateMPI.h", "da/d16/generateMPI_8h.html", "da/d16/generateMPI_8h" ],
    [ "generateRunner.cc", "d3/dad/generateRunner_8cc.html", "d3/dad/generateRunner_8cc" ],
    [ "generateRunner.h", "d2/d75/generateRunner_8h.html", "d2/d75/generateRunner_8h" ],
    [ "build/lib.linux-x86_64-3.6/pygenn/genn_groups.py", "d4/dbd/build_2lib_8linux-x86__64-3_86_2pygenn_2genn__groups_8py.html", "d4/dbd/build_2lib_8linux-x86__64-3_86_2pygenn_2genn__groups_8py" ],
    [ "pygenn/genn_groups.py", "d0/d92/pygenn_2genn__groups_8py.html", [
      [ "Group", "d1/db3/classpygenn_1_1genn__groups_1_1Group.html", "d1/db3/classpygenn_1_1genn__groups_1_1Group" ],
      [ "NeuronGroup", "dc/dc9/classpygenn_1_1genn__groups_1_1NeuronGroup.html", "dc/dc9/classpygenn_1_1genn__groups_1_1NeuronGroup" ],
      [ "SynapseGroup", "d5/d49/classpygenn_1_1genn__groups_1_1SynapseGroup.html", "d5/d49/classpygenn_1_1genn__groups_1_1SynapseGroup" ],
      [ "CurrentSource", "da/d83/classpygenn_1_1genn__groups_1_1CurrentSource.html", "da/d83/classpygenn_1_1genn__groups_1_1CurrentSource" ]
    ] ],
    [ "build/lib.linux-x86_64-3.6/pygenn/genn_model.py", "d7/d0b/build_2lib_8linux-x86__64-3_86_2pygenn_2genn__model_8py.html", "d7/d0b/build_2lib_8linux-x86__64-3_86_2pygenn_2genn__model_8py" ],
    [ "pygenn/genn_model.py", "de/d62/pygenn_2genn__model_8py.html", "de/d62/pygenn_2genn__model_8py" ],
    [ "genn_wrapper.py", "d0/dea/genn__wrapper_8py.html", "d0/dea/genn__wrapper_8py" ],
    [ "global.cc", "d7/dd8/global_8cc.html", "d7/dd8/global_8cc" ],
    [ "global.h", "d2/d49/global_8h.html", "d2/d49/global_8h" ],
    [ "hr_time.cc", "db/dd3/hr__time_8cc.html", "db/dd3/hr__time_8cc" ],
    [ "hr_time.h", "db/dd6/hr__time_8h.html", [
      [ "stopWatch", "d1/df5/structstopWatch.html", "d1/df5/structstopWatch" ],
      [ "CStopWatch", "d9/de8/classCStopWatch.html", "d9/de8/classCStopWatch" ]
    ] ],
    [ "initSparseConnectivitySnippet.cc", "d4/d88/initSparseConnectivitySnippet_8cc.html", "d4/d88/initSparseConnectivitySnippet_8cc" ],
    [ "initSparseConnectivitySnippet.h", "de/d51/initSparseConnectivitySnippet_8h.html", "de/d51/initSparseConnectivitySnippet_8h" ],
    [ "InitSparseConnectivitySnippet.py", "de/d65/InitSparseConnectivitySnippet_8py.html", "de/d65/InitSparseConnectivitySnippet_8py" ],
    [ "initVarSnippet.cc", "d1/dfe/initVarSnippet_8cc.html", "d1/dfe/initVarSnippet_8cc" ],
    [ "initVarSnippet.h", "d9/ddf/initVarSnippet_8h.html", "d9/ddf/initVarSnippet_8h" ],
    [ "InitVarSnippet.py", "d3/d08/InitVarSnippet_8py.html", "d3/d08/InitVarSnippet_8py" ],
    [ "build/lib.linux-x86_64-3.6/pygenn/model_preprocessor.py", "df/d3b/build_2lib_8linux-x86__64-3_86_2pygenn_2model__preprocessor_8py.html", "df/d3b/build_2lib_8linux-x86__64-3_86_2pygenn_2model__preprocessor_8py" ],
    [ "pygenn/model_preprocessor.py", "df/dfc/pygenn_2model__preprocessor_8py.html", "df/dfc/pygenn_2model__preprocessor_8py" ],
    [ "Models.py", "df/d26/Models_8py.html", "df/d26/Models_8py" ],
    [ "include/modelSpec.cc", "d9/d6f/include_2modelSpec_8cc.html", null ],
    [ "src/modelSpec.cc", "d8/d9a/src_2modelSpec_8cc.html", "d8/d9a/src_2modelSpec_8cc" ],
    [ "modelSpec.h", "dc/de1/modelSpec_8h.html", "dc/de1/modelSpec_8h" ],
    [ "neuronGroup.cc", "dd/de9/neuronGroup_8cc.html", null ],
    [ "neuronGroup.h", "dd/d44/neuronGroup_8h.html", [
      [ "NeuronGroup", "d7/d3b/classNeuronGroup.html", "d7/d3b/classNeuronGroup" ]
    ] ],
    [ "neuronModels.cc", "dc/dbc/neuronModels_8cc.html", "dc/dbc/neuronModels_8cc" ],
    [ "neuronModels.h", "d3/dc0/neuronModels_8h.html", "d3/dc0/neuronModels_8h" ],
    [ "NeuronModels.py", "dc/df2/NeuronModels_8py.html", "dc/df2/NeuronModels_8py" ],
    [ "newModels.h", "d4/ded/newModels_8h.html", "d4/ded/newModels_8h" ],
    [ "newNeuronModels.cc", "d1/da9/newNeuronModels_8cc.html", "d1/da9/newNeuronModels_8cc" ],
    [ "newNeuronModels.h", "d0/dcb/newNeuronModels_8h.html", "d0/dcb/newNeuronModels_8h" ],
    [ "newPostsynapticModels.cc", "d9/d9b/newPostsynapticModels_8cc.html", "d9/d9b/newPostsynapticModels_8cc" ],
    [ "newPostsynapticModels.h", "da/d05/newPostsynapticModels_8h.html", "da/d05/newPostsynapticModels_8h" ],
    [ "newWeightUpdateModels.cc", "d1/d54/newWeightUpdateModels_8cc.html", "d1/d54/newWeightUpdateModels_8cc" ],
    [ "newWeightUpdateModels.h", "d4/d0f/newWeightUpdateModels_8h.html", "d4/d0f/newWeightUpdateModels_8h" ],
    [ "postSynapseModels.cc", "d5/d21/postSynapseModels_8cc.html", "d5/d21/postSynapseModels_8cc" ],
    [ "postSynapseModels.h", "d4/d8a/postSynapseModels_8h.html", "d4/d8a/postSynapseModels_8h" ],
    [ "PostsynapticModels.py", "d4/d64/PostsynapticModels_8py.html", "d4/d64/PostsynapticModels_8py" ],
    [ "setup.py", "da/dab/setup_8py.html", "da/dab/setup_8py" ],
    [ "SharedLibraryModel.py", "d9/db3/SharedLibraryModel_8py.html", "d9/db3/SharedLibraryModel_8py" ],
    [ "SingleThreadedCPUBackend.py", "d5/d01/SingleThreadedCPUBackend_8py.html", "d5/d01/SingleThreadedCPUBackend_8py" ],
    [ "snippet.h", "de/d6c/snippet_8h.html", "de/d6c/snippet_8h" ],
    [ "Snippet.py", "d9/d6a/Snippet_8py.html", "d9/d6a/Snippet_8py" ],
    [ "sparseProjection.h", "d6/d2e/sparseProjection_8h.html", [
      [ "SparseProjection", "d9/d91/structSparseProjection.html", "d9/d91/structSparseProjection" ],
      [ "RaggedProjection", "d2/d75/structRaggedProjection.html", "d2/d75/structRaggedProjection" ]
    ] ],
    [ "sparseUtils.cc", "da/d23/sparseUtils_8cc.html", "da/d23/sparseUtils_8cc" ],
    [ "sparseUtils.h", "d8/d69/sparseUtils_8h.html", "d8/d69/sparseUtils_8h" ],
    [ "standardGeneratedSections.cc", "da/d58/standardGeneratedSections_8cc.html", null ],
    [ "standardGeneratedSections.h", "d7/d6f/standardGeneratedSections_8h.html", "d7/d6f/standardGeneratedSections_8h" ],
    [ "standardSubstitutions.cc", "d2/d64/standardSubstitutions_8cc.html", null ],
    [ "standardSubstitutions.h", "d5/db9/standardSubstitutions_8h.html", "d5/db9/standardSubstitutions_8h" ],
    [ "StlContainers.py", "de/d49/StlContainers_8py.html", "de/d49/StlContainers_8py" ],
    [ "stringUtils.h", "dd/dc3/stringUtils_8h.html", "dd/dc3/stringUtils_8h" ],
    [ "synapseGroup.cc", "da/d3e/synapseGroup_8cc.html", null ],
    [ "synapseGroup.h", "de/db0/synapseGroup_8h.html", [
      [ "SynapseGroup", "dc/dfa/classSynapseGroup.html", "dc/dfa/classSynapseGroup" ]
    ] ],
    [ "synapseMatrixType.h", "dd/dd5/synapseMatrixType_8h.html", "dd/dd5/synapseMatrixType_8h" ],
    [ "synapseModels.cc", "d9/d5b/synapseModels_8cc.html", "d9/d5b/synapseModels_8cc" ],
    [ "synapseModels.h", "d2/d5b/synapseModels_8h.html", "d2/d5b/synapseModels_8h" ],
    [ "utils.cc", "d7/da9/utils_8cc.html", "d7/da9/utils_8cc" ],
    [ "utils.h", "d5/d60/utils_8h.html", "d5/d60/utils_8h" ],
    [ "variableMode.h", "d6/d8f/variableMode_8h.html", "d6/d8f/variableMode_8h" ],
    [ "WeightUpdateModels.py", "d4/d1a/WeightUpdateModels_8py.html", "d4/d1a/WeightUpdateModels_8py" ]
];