#include <functional>
#include <numeric>

// Google test includes
#include "gtest/gtest.h"

// Autogenerated simulation code includess
#include "post_vars_in_synapse_dynamics_CODE/definitions.h"

// **NOTE** base-class for simulation tests must be
// included after auto-generated globals are includes
#include "../../utils/simulation_test_post_vars.h"

TEST_P(SimulationTestPostVars, AcceptableError)
{
  float err = 0.0f;
  float x[10][100];
  for (int i = 0; i < (int)(20.0f / DT); i++)
  {
    t = i * DT;

    // for each delay
    for (int d = 0; d < 10; d++)
    {
        // for all pre-synaptic neurons
        for (int j = 0; j < 10; j++)
        {
            // for all post-syn neurons
            for (int k = 0; k < 10; k++)
            {
                if (t > 0.0001+DT)
                {
                    x[d][(j * 10) + k] = t-2*DT+10*k;
                }
                else if(i == 0)
                {
                    x[d][(j * 10) + k] = 0.0f;
                }
            }
        }

        // Add error for this time step to total
        err += std::inner_product(&x[d][0], &x[d][100],
                                  GetTheW(d),
                                  0.0,
                                  std::plus<float>(),
                                  [](float a, float b){ return abs(a - b); });
    }

    // Step simulation
    Step();
  }

  // Check total error is less than some tolerance
  EXPECT_LT(err, 5e-2);
}

#ifndef CPU_ONLY
auto simulatorBackends = ::testing::Values(true, false);
#else
auto simulatorBackends = ::testing::Values(false);
#endif

INSTANTIATE_TEST_CASE_P(SynapseDynamics,
                        SimulationTestPostVars,
                        simulatorBackends);